gcc -o P1a P1a.c
gcc -o P3a P3a.c
gcc -o P4a P4a.c
gcc -o P4b P4b.c
gcc -o P6a P6a.c
gcc -o P6b P6b.c
gcc -o RRa RRa.c
gcc -o RRb RRb.c
gcc -o RTa RTa.c
gcc -o RTb RTb.c
gcc -o RTc RTc.c
gcc -o RTd RTd.c